#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         2
bspc config window_gap          5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color "#9399b2"
bspc config focused_border_color "#fab387"

# autostart
sxhkd &
picom --config ~/.config/picom/picom.conf &
nitrogen --restore &
dunst &
~/.config/polybar/launch.sh &
playerctld daemon &
nm-applet --indicator &
~/.config/bspwm/launch-udiskie.sh &
killall ibus-daemon &
